# Generated by Django 5.0.2 on 2024-03-13 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('nascimento', models.DateField()),
                ('naturalidade', models.CharField(max_length=200)),
                ('mae', models.CharField(max_length=200)),
                ('rg', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Negado')], default=0)),
                ('campus', models.IntegerField(choices=[(0, 'UFMT - Campus Araguaia'), (1, 'UFMT - Campus Cuiabá'), (2, 'UFMT - Campus Sinop')], default=0)),
                ('curso', models.IntegerField(choices=[(0, 'Agronomia'), (1, 'Ciência da Computação'), (2, 'Engenharia da Computação'), (3, 'Física'), (4, 'Geografia'), (5, 'História'), (6, 'Letras'), (7, 'Matemáica'), (8, 'Medicina')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
