# Generated by Django 5.0.3 on 2024-03-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Aluno')], null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nascimento', models.DateField()),
                ('naturalidade', models.CharField(max_length=200)),
                ('mae', models.CharField(max_length=200)),
                ('rg', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
