# Generated by Django 5.0.2 on 2024-03-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='curso',
            field=models.IntegerField(choices=[(0, 'Agronomia'), (1, 'Ciência da Computação'), (2, 'Engenharia da Computação'), (3, 'Física'), (4, 'Geografia'), (5, 'História'), (6, 'Letras'), (7, 'Matemática'), (8, 'Medicina')], default=0),
        ),
    ]
