# Generated by Django 5.0.3 on 2024-03-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_estudante_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='imgcomp',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='imgrg',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
