# Generated by Django 5.0.3 on 2024-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_perfil_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
